In [1]:
import numpy as np
import random

In [3]:
# 创建数组
a = np.array([1,2,3,4,5,6,7])
b = np.array(range(7))
c = np.arange(7)

print(type(a))
print(a.dtype)
print(a)

print(type(b))
print(b.dtype)
print(b)

print(type(b))
print(b.dtype)
print(c)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]


In [6]:
# numpy数据类型
a = np.array(range(7), dtype=np.int64)
b = np.array(range(7), dtype='int64')
c = np.array([0,1,1,1,0], dtype=np.bool)

print(a.dtype)
print(b.dtype)
print(c)
print(c.dtype)

int64
int64
[False  True  True  True False]
bool


In [7]:
# 调整数据类型
a = np.array([0,0,0,1,1,1], dtype=np.bool)
print(a)
print(a.dtype)

b = a.astype('int8')
print(b)
print(b.dtype)

[False False False  True  True  True]
bool
[0 0 0 1 1 1]
int8


In [13]:
# numpy中的小数
a = np.array([random.random() for i in range(7)])
print(a)

b = np.round(a, 2)
print(b)

c = np.round(a, 3)
print(c)

[0.216204   0.58072607 0.61073908 0.93731106 0.88482472 0.10907072
 0.39171992]
[0.22 0.58 0.61 0.94 0.88 0.11 0.39]
[0.216 0.581 0.611 0.937 0.885 0.109 0.392]


In [6]:
# 查看数组的形状
a = np.array([[1,2,3],[4,6,7]])
print(a.shape)

b = a.reshape(3,2)
print(b)

c = np.arange(24).reshape(2,3,4)
print(c)

(2, 3)
[[1 2]
 [3 4]
 [6 7]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
# 数组展开
a = np.arange(24).reshape(2,3,4)
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
# 数组的广播
## 广播原则：如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符
##           或其中一方的长度为1，则认为它们是广播兼容的。
## 例：（3，3，3，2）——>（3，3，2）——>（3，2）
            
a = np.arange(24).reshape(2,3,4)
print(a)

b = a + 2
print(b)

c = a * 2
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]]


In [10]:
# 维度相同的数组运算
a = np.arange(24).reshape(4,6)
b = np.arange(100,124).reshape(4,6)

c = a + b
d = a * b

print(c)
print(d)

[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]
 [1344 1469 1596 1725 1856 1989]
 [2124 2261 2400 2541 2684 2829]]


In [4]:
 # 数组的转置
a = np.arange(24).reshape(4,6)
print(a)
b = a.T
print(b.shape)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(6, 4)
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [10]:
# 索引与切片 (a:b，含a不含b)
a = np.arange(24).reshape(6,4)
print(a)
# # 取一行
print('取一行')
print(a[1])
# # 取一列
print('取一列')
print(a[: , 2])
# # 取多行
print('取多行')
print(a[1:2])
print(a[[0,2,5]])
# # 取多列
print('取多列')
print(a[: , 0:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
取一行
[4 5 6 7]
取一列
[ 2  6 10 14 18 22]
取多行
[[4 5 6 7]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [20 21 22 23]]
取多列
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]


In [19]:
# numpy中数值的修改
a = np.arange(24).reshape(6,4)
print(a)
a[2:4,1:3] = 0
print(a)
# # 将小于10的数字替换为7
print(a < 10)
a[a<10] = 7
print(a)
# # np.where()
np.where(a<10,0,100)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  0  0 11]
 [12  0  0 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False  True  True False]
 [False False False False]
 [False False False False]]
[[ 7  7  7  7]
 [ 7  7  7  7]
 [ 7  7  7 11]
 [12  7  7 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0, 100],
       [100,   0,   0, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [7]:
# 数组的拼接
a = np.arange(24).reshape(4,6)
b = np.arange(100,124).reshape(4,6)

# # 竖直拼接vstack 需传元组
c = np.vstack((a, b))
print(c)

# # 水平拼接
d = np.hstack((a, b))
print(d)

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]
 [100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
[[  0   1   2   3   4   5 100 101 102 103 104 105]
 [  6   7   8   9  10  11 106 107 108 109 110 111]
 [ 12  13  14  15  16  17 112 113 114 115 116 117]
 [ 18  19  20  21  22  23 118 119 120 121 122 123]]


In [12]:
# 数组的行列互换
a = np.arange(24).reshape(4,6)

# # 行交换
a[[0,1],:] = a[[1,0],:]
print(a)

# # 列交换
a[:,[0,5]] = a[:,[5,0]]
print(a)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[11  7  8  9 10  6]
 [ 5  1  2  3  4  0]
 [17 13 14 15 16 12]
 [23 19 20 21 22 18]]


In [20]:
# 获取最小、大值的位置
a = np.arange(24).reshape(4,6)
print(a)
b = np.argmax(a, axis=1)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[5 5 5 5]


In [22]:
# 创建一个全0的数组
a = np.zeros((3, 4))
print(a)

# 创建一个全1的数组
b = np.ones((3, 4))
print(b)

# 创建一个对角线为1的正方形数组
c = np.eye(3)
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# nan的注意点
a = np.random.randint(1, 77, (3,4))
a = a.astype('float32')

a[0,3] = np.nan
a[2,0] = np.nan

print(a)

# # 判断数组中nan的个数
b = np.count_nonzero(a != a)
print(b)

c = np.isnan(a)
print(c)
d = np.count_nonzero(c)
print(d)

[[27. 17. 32. nan]
 [73. 62. 76. 11.]
 [nan 51. 10. 67.]]
2
[[False False False  True]
 [False False False False]
 [ True False False False]]
2


In [49]:
# numpy中常用的统计函数，默认返回多维数组的全部的统计结果，如果指定axis，则返回一个当前轴上的结果
np.random.seed(777)
t = np.random.randint(1, 100, (4,6))
print(t)
print("*" * 20)

# # 求和 t.sum(axis = None)
print(t.sum(axis = 0))

# # 均值 t.mean(axis=None)
print(t.mean(axis = 1))

# # 中值 np.median(t, axis=None)
print(np.median(t, axis=1))

# # 最大值 t.max(axis = None)
print(t.max(axis=0))

# # 最小值 t.min(axis = None)
print(t.min(axis=1))

# # 极值 np.ptp(t, axis=None)
print(np.ptp(t, axis=0))

# # 标准差 t.std(axis = None)
print(t.std(axis=0))

[[48 60 39 88 50 72]
 [30 40 90 47 25 40]
 [19 14 15 33 92 66]
 [83 85 70  8 66 32]]
********************
[180 199 214 176 233 210]
[59.5        45.33333333 39.83333333 57.33333333]
[55. 40. 26. 68.]
[83 85 90 88 92 72]
[39 25 14  8]
[64 71 75 80 67 40]
[24.25901894 26.08040452 28.70975444 28.99137803 24.35544087 16.87453703]


In [56]:
# 将 nan 替换为列的平均数
t = np.random.randint(10, 21, (3,4)).astype('float32')
t[1, 2:] = np.nan
print(t)

for i in range(t.shape[1]):
    # 当前列
    temp_col = t[:, i]
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 当前列有nan
    if nan_num != 0:
        # 不为nan 
        temp_not_nan_col = temp_col[temp_col == temp_col]
        temp_col[np.isnan(temp_col)] = temp_not_nan_col.mean()
        
print(t)

[[16. 14. 13. 17.]
 [10. 14. nan nan]
 [11. 17. 18. 15.]]
[[16.  14.  13.  17. ]
 [10.  14.  15.5 16. ]
 [11.  17.  18.  15. ]]
