In [8]:
import numpy as np
import random

In [3]:
# 创建数组
a = np.array([1,2,3,4,5,6,7])
b = np.array(range(7))
c = np.arange(7)

print(type(a))
print(a.dtype)
print(a)

print(type(b))
print(b.dtype)
print(b)

print(type(b))
print(b.dtype)
print(c)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]


In [6]:
# numpy数据类型
a = np.array(range(7), dtype=np.int64)
b = np.array(range(7), dtype='int64')
c = np.array([0,1,1,1,0], dtype=np.bool)

print(a.dtype)
print(b.dtype)
print(c)
print(c.dtype)

int64
int64
[False  True  True  True False]
bool


In [7]:
# 调整数据类型
a = np.array([0,0,0,1,1,1], dtype=np.bool)
print(a)
print(a.dtype)

b = a.astype('int8')
print(b)
print(b.dtype)

[False False False  True  True  True]
bool
[0 0 0 1 1 1]
int8


In [13]:
# numpy中的小数
a = np.array([random.random() for i in range(7)])
print(a)

b = np.round(a, 2)
print(b)

c = np.round(a, 3)
print(c)

[0.216204   0.58072607 0.61073908 0.93731106 0.88482472 0.10907072
 0.39171992]
[0.22 0.58 0.61 0.94 0.88 0.11 0.39]
[0.216 0.581 0.611 0.937 0.885 0.109 0.392]
