In [1]:
import numpy as np
import random

In [3]:
# 创建数组
a = np.array([1,2,3,4,5,6,7])
b = np.array(range(7))
c = np.arange(7)

print(type(a))
print(a.dtype)
print(a)

print(type(b))
print(b.dtype)
print(b)

print(type(b))
print(b.dtype)
print(c)

<class 'numpy.ndarray'>
int32
[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
[0 1 2 3 4 5 6]


In [6]:
# numpy数据类型
a = np.array(range(7), dtype=np.int64)
b = np.array(range(7), dtype='int64')
c = np.array([0,1,1,1,0], dtype=np.bool)

print(a.dtype)
print(b.dtype)
print(c)
print(c.dtype)

int64
int64
[False  True  True  True False]
bool


In [7]:
# 调整数据类型
a = np.array([0,0,0,1,1,1], dtype=np.bool)
print(a)
print(a.dtype)

b = a.astype('int8')
print(b)
print(b.dtype)

[False False False  True  True  True]
bool
[0 0 0 1 1 1]
int8


In [13]:
# numpy中的小数
a = np.array([random.random() for i in range(7)])
print(a)

b = np.round(a, 2)
print(b)

c = np.round(a, 3)
print(c)

[0.216204   0.58072607 0.61073908 0.93731106 0.88482472 0.10907072
 0.39171992]
[0.22 0.58 0.61 0.94 0.88 0.11 0.39]
[0.216 0.581 0.611 0.937 0.885 0.109 0.392]


In [6]:
# 查看数组的形状
a = np.array([[1,2,3],[4,6,7]])
print(a.shape)

b = a.reshape(3,2)
print(b)

c = np.arange(24).reshape(2,3,4)
print(c)

(2, 3)
[[1 2]
 [3 4]
 [6 7]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
# 数组展开
a = np.arange(24).reshape(2,3,4)
b = a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
# 数组的广播
## 广播原则：如果两个数组的后缘维度（即从末尾开始算起的维度）的轴长度相符
##           或其中一方的长度为1，则认为它们是广播兼容的。
## 例：（3，3，3，2）——>（3，3，2）——>（3，2）
            
a = np.arange(24).reshape(2,3,4)
print(a)

b = a + 2
print(b)

c = a * 2
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]
  [22 23 24 25]]]
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]]


In [10]:
# 维度相同的数组运算
a = np.arange(24).reshape(4,6)
b = np.arange(100,124).reshape(4,6)

c = a + b
d = a * b

print(c)
print(d)

[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]
 [1344 1469 1596 1725 1856 1989]
 [2124 2261 2400 2541 2684 2829]]


In [4]:
 # 数组的转置
a = np.arange(24).reshape(4,6)
print(a)
b = a.T
print(b.shape)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(6, 4)
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [10]:
# 索引与切片 (a:b，含a不含b)
a = np.arange(24).reshape(6,4)
print(a)
# # 取一行
print('取一行')
print(a[1])
# # 取一列
print('取一列')
print(a[: , 2])
# # 取多行
print('取多行')
print(a[1:2])
print(a[[0,2,5]])
# # 取多列
print('取多列')
print(a[: , 0:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
取一行
[4 5 6 7]
取一列
[ 2  6 10 14 18 22]
取多行
[[4 5 6 7]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [20 21 22 23]]
取多列
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]
 [20 21 22]]


In [19]:
# numpy中数值的修改
a = np.arange(24).reshape(6,4)
print(a)
a[2:4,1:3] = 0
print(a)
# # 将小于10的数字替换为7
print(a < 10)
a[a<10] = 7
print(a)
# # np.where()
np.where(a<10,0,100)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  0  0 11]
 [12  0  0 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False  True  True False]
 [False False False False]
 [False False False False]]
[[ 7  7  7  7]
 [ 7  7  7  7]
 [ 7  7  7 11]
 [12  7  7 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0, 100],
       [100,   0,   0, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])